# Generated by Django 5.2.4 on 2025-08-05 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="記録する日付",
                        unique=True,
                        verbose_name="日付",
                    ),
                ),
                (
                    "weather",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sunny", "晴れ"),
                            ("cloudy", "くもり"),
                            ("rainy", "雨"),
                        ],
                        max_length=10,
                        verbose_name="天気",
                    ),
                ),
                (
                    "max_pressure",
                    models.IntegerField(
                        blank=True,
                        help_text="ヘクトパスカルで入力",
                        null=True,
                        verbose_name="最高気圧 (hPa)",
                    ),
                ),
                (
                    "min_pressure",
                    models.IntegerField(
                        blank=True,
                        help_text="ヘクトパスカルで入力",
                        null=True,
                        verbose_name="最低気圧 (hPa)",
                    ),
                ),
                (
                    "max_temperature",
                    models.FloatField(
                        blank=True,
                        help_text="摂氏で入力",
                        null=True,
                        verbose_name="最高気温 (°C)",
                    ),
                ),
                (
                    "min_temperature",
                    models.FloatField(
                        blank=True,
                        help_text="摂氏で入力",
                        null=True,
                        verbose_name="最低気温 (°C)",
                    ),
                ),
                (
                    "humidity",
                    models.IntegerField(
                        blank=True,
                        help_text="パーセントで入力",
                        null=True,
                        verbose_name="湿度 (%)",
                    ),
                ),
                (
                    "pollen",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "S"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                        ],
                        help_text="Sが最も少なく、Dが最も多い",
                        max_length=1,
                        verbose_name="花粉状況",
                    ),
                ),
                (
                    "pm25",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "S"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                        ],
                        help_text="Sが最も空気がきれいで、Dが最も汚れている",
                        max_length=1,
                        verbose_name="PM2.5飛散状況",
                    ),
                ),
                (
                    "my_mood",
                    models.CharField(
                        choices=[
                            ("S", "S"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                        ],
                        help_text="Sが最も機嫌が良い",
                        max_length=1,
                        verbose_name="自分の機嫌",
                    ),
                ),
                (
                    "wife_mood",
                    models.CharField(
                        choices=[
                            ("S", "S"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                        ],
                        help_text="Sが最も機嫌が良い",
                        max_length=1,
                        verbose_name="妻の機嫌",
                    ),
                ),
                (
                    "headache_medicine",
                    models.CharField(
                        choices=[("yes", "〇"), ("no", "×"), ("unknown", "不明")],
                        default="unknown",
                        max_length=10,
                        verbose_name="頭痛薬接種",
                    ),
                ),
                (
                    "mishap",
                    models.BooleanField(
                        default=False,
                        help_text="自分や家族（妻以外）の失態",
                        verbose_name="失態の有無",
                    ),
                ),
                ("diary", models.TextField(blank=True, verbose_name="日記")),
            ],
            options={
                "verbose_name": "日々の記録",
                "verbose_name_plural": "日々の記録",
                "ordering": ["-date"],
            },
        ),
    ]
