databases:
  - name: postgres
    plan: free

services:
  - type: web
    name: daily-management-app
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn project_config.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: BASIC_AUTH_USER
        value: "torohi"
      - key: BASIC_AUTH_PASSWORD
        generateValue: true # Generates a random password, user should set their own
      - key: WEB_CONCURRENCY
        value: "1"
