databases:
  - name: postgres
    plan: free

services:
  - type: web
    name: daily-management-app
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn project_config.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: OPENWEATHER_API_KEY
        # IMPORTANT: Replace this with your actual API key in the Render dashboard
        value: "YOUR_API_KEY_HERE"
      - key: WEB_CONCURRENCY
        value: 4
