services:
  # A PostgreSQL database service
  - type: db
    name: postgres
    plan: free # Use the free tier for the database
    postgresMajorVersion: 13

  # The Django web service
  - type: web
    name: daily-management-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn daily_management.daily_management.wsgi"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: db # Match the database service type
          name: postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
