# Generated by Django 5.2.4 on 2025-08-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyrecord",
            name="max_pressure",
            field=models.FloatField(
                blank=True,
                help_text="ヘクトパスカルで入力",
                null=True,
                verbose_name="最高気圧 (hPa)",
            ),
        ),
        migrations.AlterField(
            model_name="dailyrecord",
            name="min_pressure",
            field=models.FloatField(
                blank=True,
                help_text="ヘクトパスカルで入力",
                null=True,
                verbose_name="最低気圧 (hPa)",
            ),
        ),
    ]
